#Load the CSV file into data variable one after the other
data = read.csv(file.choose(),na.strings=c(""),encoding="UTF-8")
head(data)

vehicles <- subset (data, select = -c(X.U.FEFF.UNIQUE_ID, VEHICLE_ID, STATE_REGISTRATION, VEHICLE_MAKE, VEHICLE_MODEL, VEHICLE_YEAR, TRAVEL_DIRECTION, 
                                      VEHICLE_OCCUPANTS, DRIVER_SEX, DRIVER_LICENSE_STATUS, DRIVER_LICENSE_JURISDICTION, PRE_CRASH,
                                      POINT_OF_IMPACT, VEHICLE_DAMAGE, VEHICLE_DAMAGE_1, VEHICLE_DAMAGE_2, VEHICLE_DAMAGE_3, 
                                      PUBLIC_PROPERTY_DAMAGE, PUBLIC_PROPERTY_DAMAGE_TYPE, CONTRIBUTING_FACTOR_1, CONTRIBUTING_FACTOR_2))

colnames(vehicles) <- c('Collision_ID','Crash_Date','Crash_Time','Vehicle_Type')
head(vehicles)

vehicles$Crash_Date <- as.POSIXct(vehicles$Crash_Date, format="%m/%d/%Y")
vehicles$Crash_Date <- as.Date(vehicles$Crash_Date,format = "%Y-%m-%d")
vehicles <- vehicles[rev(order(vehicles$Crash_Date)),]

str(vehicles)
vehicles <- vehicles[!is.na(vehicles$Vehicle_Type),]
vehicles$Vehicle_Type <- as.factor(vehicles$Vehicle_Type)

vehicles$Vehicle_Type <- gsub("3-Door","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("2 dr sedan","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("AMBULANCE","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("ambulance","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("bay crane","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Box Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Cement tru","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Chassis Cab","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("crane boom","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("E-SCOOTER","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FDNY FIRE","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("LIMO","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Moped","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Motorcycle","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("NonMotordS","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("PK","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("RMP","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("School Bus","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SMYELLSCHO","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Station Wagon/Sport Utility Vehicle","SUV",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("TLR","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Tractor Truck Gasoline","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("UNKNOWN","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("van","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("4 dr sedan","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Armored Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Bus","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("commercial","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Dump","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("EC3","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FDNY Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Flat Bed","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("GAS MO-PED","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Lunch Wagon","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MOPED","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Motorscooter","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Open Body","SUV",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("police rep","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SANITATION","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SCHOOL BUS","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Stake or Rack","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("STREET SWE","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("tow truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("TRAILER","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Unknown ve","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("AMBU","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Van","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Beverage Truck","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Busv","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Concrete Mixer","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("E-Bike","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("ELECTRIC M","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("fire truck","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Flat Rack","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Glass Rack","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Mack Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Motor Scoo","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MTA BUS","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Pedicab","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Ram","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SCHOOL BU","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Sedan","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Standing s","Taxi",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Tanker","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Tow Truck / Wrecker","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Trl","Taxi",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("USPS MAIL","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("wheel load","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Ambulance","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Bike","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Carry All","Taxi",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Convertible","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("E-Scooter","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FDNY AMBUL","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FIRE TRUCK","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FORKLIFT","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Lift Boom","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MO PED","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Motorbike","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Multi-Wheeled Vehicle","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Pick-up Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Refrigerated Van","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("School bus","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("STATION WA","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Taxi","Taxi",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Tractor Truck Diesel","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("USPS POSTA","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("work truck","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FDNY AmbulanceL","Ambulance",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Firetruck","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Garbage or Refuse","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Refrigerated Commercial Vehicle","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Constructi","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("GMC DELIVE","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FIRE ENGIN","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("GARBAGE TR","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("moped","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Moped scoo","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MTA BUS","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Pallet","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Suburban","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Unk","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("ELECTRIC S","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FORD TRANS","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("GAS MO-PED","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Mack","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MOPPED","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Moped scoo","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MTA BUS","Bus",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Multi-Wheeled Vehicle","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Suburban","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Unk","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("BOX TRUCK","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Enclosed Body - Removable Enclosure","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("ESCOOTER S","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FDNY","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Fire Heavy Vehicle","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Fire truck","Fire Engine",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("FLAT","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("GAS Two Wheeler","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("LIMIT USE","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("MOTOR SCOO","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Motorscoot","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("PICK-UP TR","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Pick up","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SCOOTER","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("SEDAN","Sedan",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Tow Heavy Vehicle","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("TOW TRUCK","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("TRACTOR","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Trailer","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Two Wheeler clas","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("Two Wheeler scoo","Two Wheeler",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("UHAUL VAN","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("UNK","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("USPS","Commercial Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("UTILITY TR","Heavy Vehicle",vehicles$Vehicle_Type)
vehicles$Vehicle_Type <- gsub("VMS","Commercial Vehicle",vehicles$Vehicle_Type)


vehicles$Vehicle_Type <- as.factor(vehicles$Vehicle_Type)
levels(vehicles$Vehicle_Type)
summary(vehicles)
head(vehicles)

#Export the cleaned data
write.csv(vehicles,"C:\\Users\\prath\\Desktop\\vehicles.csv")

#persons[!complete.cases(persons$Person_Role),]
